service: streamer

frameworkVersion: "3"

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-2
  runtime: python3.9
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "kinesisvideo:*"
      Resource: "*"

package:
  exclude:
    - node_modules/**
    - venv/**

functions:
  streamer:
    handler: aws_lambda.handler
    environment:
      STREAM_NAME: ${env:STREAM_NAME}
      VIDEO_FILE_PATH: ${env:VIDEO_FILE_PATH}
    events:
      - http:
          path: upload
          method: get
          cors: true

plugins:
  - serverless-python-requirements
